### ISSUE TITLE
Cool project!

### ISSUE THREAD

**Issue by msurguy** [gcpreston/webcandy#22]
Hi! 

I'm currently brainstorming a little app for my Fadecandy and found this repo through Github search. 

I'm excited to give this a go and see what kind of effects I can run on this thing! 

I was wondering if you needed help with anything UI related, product related or need any graphic assets for the UI / any screens. Might be able to help out a little there! 

Also, if you need some custom Bootstrap theme, I'm pretty good at Bootstrap!

**Comment by gcpreston** [comment]
Hello, thanks for checking out the project! Just saw this now, definitely let me know how setting up goes. Nobody except me has tried to run the setup yet, but I tried to make it easy, so I definitely want to know if it works and would love feedback for how to improve it.

I have a couple of open issues I could use some help with. If you know how to do UI stuff, you could take a look at #15, it's something I've had a vision for how it should work but not so much what it should actually look like.

Also, if you know how to make graphics I've been thinking that this needs a logo for a while now. It's not a huge priority or anything, but if you have any ideas I would love to check them out!

Let me know if you have any questions, comments, or suggestions :)

**Comment by gcpreston** [comment]
Also, if you want to just try using Webcandy without setting up your own dev environment first, I have a version running on AWS currently. You can use it by running [the client](https://github.com/gcpreston/webcandy-client) and pointing it to the EC2 instance.

`python client.py testuser1 Webcandy1 testclient1 --host <IP> --port 6543 --app-port 8080`

If this is something you'd want to do, I can email you the elastic IP, just to not have it on public GitHub.

**Comment by msurguy** [comment]
Hi! 

I was able to whip up a logo real quick, following a very non-scientific process of trying out different fonts and keeping a theme of LED lights. See options 1-3 below: 
<img width="726" alt="Screen Shot 2019-06-24 at 2 08 34 PM" src="https://user-images.githubusercontent.com/585833/60052327-cfa69e80-9689-11e9-8096-7b0cd089df3e.png">

For a more methodical approach for the logo and overall website style guide, we'd need to put together a Pinterest board containing some visual inspiration. For an example, see my board that I put together to inspire the visual look of https://drawingbots.net/ : https://pin.it/6fzm6kg3kx2fxv 

If you let me know the overall direction / style, I might be able to narrow down a bit better on the concrete design. 

Unfortunately I don't have time right now to set everything up locally, but if you could email me the EC2 IP and the command necessary to hook up the client, I can try this project soon. My email is same as my username + gmail.

**Comment by gcpreston** [comment]
I really like that second logo! Honestly, right now I don't have that much direction/style, but I've been using Bootstrap for as much of the (currently, minimal) UI, so there is a general color/style theme. Here is an image of what the site currently looks like:

![ui](https://user-images.githubusercontent.com/7387903/60296988-485d6300-98f5-11e9-811d-aff28a46f7bc.png)

I'd like to keep using the general Bootstrap theme, mainly for consistency and simplicity, so anything that can fit into that would work well. I've never done any formal UI design work, but I'd be happy to work with you fleshing out ideas via Pinterest.

I'll email you the EC2 details and connection instructions shortly. Thanks for your help!
